# Generated by Django 5.1.7 on 2025-03-10 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creacion_y_gestion_de_productos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
