# Generated by Django 5.1.7 on 2025-03-11 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creacion_y_gestion_de_productos', '0003_alter_producto_descripcion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto_Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
