# Generated by Django 5.1.7 on 2025-03-17 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creacion_y_gestion_de_productos', '0004_producto_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ALMACENABLE', 'Almacenable'), ('CONSUMIBLE', 'Consumible'), ('SERVICIO', 'Servicio')], max_length=20, unique=True)),
            ],
        ),
    ]
