# Generated by Django 5.1.7 on 2025-03-17 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('creacion_y_gestion_de_productos', '0005_tipoproducto'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TipoProducto',
        ),
    ]
