# Generated by Django 5.1.7 on 2025-03-17 22:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creacion_y_gestion_de_productos', '0006_delete_tipoproducto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto_Tipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('almacenable', 'Almacenable'), ('consumible', 'Consumible'), ('servicio', 'Servicio')], default='almacenable', max_length=11, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='producto',
            name='descripcion',
            field=models.TextField(default='Descripción no disponible'),
        ),
        migrations.AddField(
            model_name='producto',
            name='tipo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='creacion_y_gestion_de_productos.producto_tipo'),
        ),
    ]
