# Generated by Django 5.1.7 on 2025-03-18 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('creacion_y_gestion_de_productos', '0007_producto_tipo_alter_producto_descripcion_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Producto_Tipo',
            new_name='ProductoTipo',
        ),
    ]
