# Generated by Django 5.1.7 on 2025-03-18 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creacion_y_gestion_de_productos', '0008_rename_producto_tipo_productotipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productotipo',
            name='tipo',
            field=models.CharField(choices=[('almacenable', 'almacenable'), ('consumible', 'consumible'), ('servicio', 'servicio')], default='almacenable', max_length=11, unique=True),
        ),
    ]
