# Generated by Django 5.1.7 on 2025-03-18 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creacion_y_gestion_de_productos', '0009_alter_productotipo_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productotipo',
            name='tipo',
            field=models.CharField(choices=[('almacenable', 'Almacenable'), ('consumible', 'Consumible'), ('servicio', 'Servicio')], max_length=100, unique=True),
        ),
    ]
