# Generated by Django 5.1.7 on 2025-03-18 20:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creacion_y_gestion_de_productos', '0011_alter_producto_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductoCategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='creacion_y_gestion_de_productos.productocategoria')),
            ],
        ),
        migrations.DeleteModel(
            name='Producto_Categoria',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='tipo',
            new_name='tipo_producto',
        ),
        migrations.AddField(
            model_name='producto',
            name='categoria',
            field=models.ManyToManyField(related_name='productos', to='creacion_y_gestion_de_productos.productocategoria'),
        ),
    ]
