# Generated by Django 5.1.7 on 2025-03-18 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creacion_y_gestion_de_productos', '0013_remove_producto_categoria_producto_presentacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='categoria',
            field=models.ManyToManyField(related_name='productos', to='creacion_y_gestion_de_productos.productocategoria'),
        ),
    ]
