# Generated by Django 5.1.7 on 2025-03-19 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creacion_y_gestion_de_productos', '0015_productoprecio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productoprecio',
            name='precio',
            field=models.DecimalField(decimal_places=4, max_digits=100),
        ),
    ]
