# Generated by Django 5.1.7 on 2025-03-19 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creacion_y_gestion_de_productos', '0016_alter_productoprecio_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='precio',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='creacion_y_gestion_de_productos.productoprecio'),
            preserve_default=False,
        ),
    ]
