# Generated by Django 5.1.7 on 2025-03-19 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('creacion_y_gestion_de_productos', '0017_producto_precio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='done',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='tipo_producto',
        ),
    ]
