# Generated by Django 5.1.7 on 2025-03-19 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creacion_y_gestion_de_productos', '0018_remove_producto_categoria_remove_producto_done_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
