# Generated by Django 5.1.7 on 2025-03-19 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creacion_y_gestion_de_productos', '0019_producto_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='tipo_producto',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='creacion_y_gestion_de_productos.productotipo'),
            preserve_default=False,
        ),
    ]
