# Generated by Django 5.1.7 on 2025-03-19 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creacion_y_gestion_de_productos', '0020_producto_tipo_producto'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductoPrecioCoste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_coste', models.DecimalField(decimal_places=4, max_digits=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Precio coste',
                'verbose_name_plural': 'Precios costes',
            },
        ),
        migrations.CreateModel(
            name='ProductoPrecioVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_venta', models.DecimalField(decimal_places=4, max_digits=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Precio venta',
                'verbose_name_plural': 'Precios ventas',
            },
        ),
        migrations.AddField(
            model_name='producto',
            name='precio_coste',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='creacion_y_gestion_de_productos.productopreciocoste'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='precio_venta',
            field=models.OneToOneField(default=0.0, on_delete=django.db.models.deletion.CASCADE, to='creacion_y_gestion_de_productos.productoprecioventa'),
            preserve_default=False,
        ),
    ]
