# Generated by Django 5.1.7 on 2025-03-20 02:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creacion_y_gestion_de_productos', '0021_productopreciocoste_productoprecioventa_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnidadMedida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('abreviatura', models.CharField(max_length=10)),
                ('factor_conversion', models.DecimalField(decimal_places=4, max_digits=10)),
            ],
        ),
        migrations.AlterField(
            model_name='producto',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='creacion_y_gestion_de_productos.productoprecio'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio_coste',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos_coste', to='creacion_y_gestion_de_productos.productopreciocoste'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio_venta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos_venta', to='creacion_y_gestion_de_productos.productoprecioventa'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='presentacion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='ConversionUnidadMedida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factor_conversion', models.DecimalField(decimal_places=4, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversiones', to='creacion_y_gestion_de_productos.producto')),
                ('unidad_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversiones_destino', to='creacion_y_gestion_de_productos.unidadmedida')),
                ('unidad_origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversiones_origen', to='creacion_y_gestion_de_productos.unidadmedida')),
            ],
        ),
        migrations.AddField(
            model_name='producto',
            name='unidades_alternativas',
            field=models.ManyToManyField(through='creacion_y_gestion_de_productos.ConversionUnidadMedida', to='creacion_y_gestion_de_productos.unidadmedida'),
        ),
    ]
