# Generated by Django 5.1.7 on 2025-03-20 02:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creacion_y_gestion_de_productos', '0022_unidadmedida_alter_producto_descripcion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='uom_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='productos_principales', to='creacion_y_gestion_de_productos.unidadmedida', unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='uom_po_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='productos_compra', to='creacion_y_gestion_de_productos.unidadmedida', unique=True),
            preserve_default=False,
        ),
    ]
