# Generated by Django 5.1.7 on 2025-03-20 02:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creacion_y_gestion_de_productos', '0023_producto_uom_id_producto_uom_po_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='unidades_alternativas',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='uom_id',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='uom_po_id',
        ),
        migrations.AlterField(
            model_name='producto',
            name='descripcion',
            field=models.TextField(default='Descripción no disponible'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='creacion_y_gestion_de_productos.productoprecio'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio_coste',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='creacion_y_gestion_de_productos.productopreciocoste'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio_venta',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='creacion_y_gestion_de_productos.productoprecioventa'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='presentacion',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ConversionUnidadMedida',
        ),
        migrations.DeleteModel(
            name='UnidadMedida',
        ),
    ]
