# Generated by Django 5.1.7 on 2025-03-20 15:31

import creacion_y_gestion_de_productos.models.models_category
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creacion_y_gestion_de_productos', '0025_productcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='categ',
            field=models.ForeignKey(default=creacion_y_gestion_de_productos.models.models_category.ProductCategory.get_default_category, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='creacion_y_gestion_de_productos.productcategory'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='creacion_y_gestion_de_productos.productoprecio'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio_coste',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='creacion_y_gestion_de_productos.productopreciocoste'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio_venta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='creacion_y_gestion_de_productos.productoprecioventa'),
        ),
        migrations.DeleteModel(
            name='ProductoCategoria',
        ),
    ]
