# Generated by Django 5.1.7 on 2025-03-20 19:42

import creacion_y_gestion_de_productos.models.models_category
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creacion_y_gestion_de_productos', '0027_remove_producto_categ_producto_categoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='categoria',
        ),
        migrations.AddField(
            model_name='producto',
            name='categ',
            field=models.ForeignKey(default=creacion_y_gestion_de_productos.models.models_category.ProductCategory.get_default_category, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='creacion_y_gestion_de_productos.productcategory'),
        ),
    ]
