# Generated by Django 5.1.7 on 2025-03-20 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creacion_y_gestion_de_productos', '0028_remove_producto_categoria_producto_categ'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='categ',
        ),
        migrations.AddField(
            model_name='producto',
            name='categoria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='creacion_y_gestion_de_productos.productcategory'),
            preserve_default=False,
        ),
    ]
