# Generated by Django 5.1.7 on 2025-03-22 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creacion_y_gestion_de_productos', '0029_remove_producto_categ_producto_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='codigo_barras',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='codigo_ncm',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='codigo_producto_interno',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='codigo_producto_proveedor',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='referencia',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='descripcion',
            field=models.TextField(default='Descripción no disponible', null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='presentacion',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
