# Generated by Django 5.1.7 on 2025-03-22 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('creacion_y_gestion_de_productos', '0030_producto_codigo_barras_producto_codigo_ncm_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='codigo_barras',
            new_name='cod_barras',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='codigo_ncm',
            new_name='cod_ncm',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='codigo_producto_interno',
            new_name='cod_prod_interno',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='codigo_producto_proveedor',
            new_name='cod_prod_proveedor',
        ),
    ]
