# Generated by Django 5.1.7 on 2025-03-24 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creacion_y_gestion_de_productos', '0031_rename_codigo_barras_producto_cod_barras_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='creacion_y_gestion_de_productos.productcategory'),
        ),
    ]
