# Generated by Django 5.1.7 on 2025-03-24 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creacion_y_gestion_de_productos', '0032_alter_producto_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_attribute', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductAttributeValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('name_attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='creacion_y_gestion_de_productos.productattribute')),
            ],
        ),
        migrations.CreateModel(
            name='ProductProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('cod_barras', models.CharField(blank=True, max_length=100, null=True)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('product_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variantes', to='creacion_y_gestion_de_productos.producto')),
            ],
        ),
        migrations.CreateModel(
            name='ProductTemplateAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='creacion_y_gestion_de_productos.productattribute')),
                ('product_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atributos_permitidos', to='creacion_y_gestion_de_productos.producto')),
            ],
        ),
        migrations.CreateModel(
            name='ProductTemplateAttributeValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute_value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='creacion_y_gestion_de_productos.productattributevalue')),
                ('product_variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atributos_asignados', to='creacion_y_gestion_de_productos.productproduct')),
            ],
        ),
        migrations.AddField(
            model_name='productproduct',
            name='attributes',
            field=models.ManyToManyField(through='creacion_y_gestion_de_productos.ProductTemplateAttributeValue', to='creacion_y_gestion_de_productos.productattributevalue'),
        ),
    ]
