# Generated by Django 5.1.7 on 2025-03-28 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('creacion_y_gestion_de_productos', '0034_attributename_attributevalue_attributenamevalue'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attributename',
            old_name='name_attr',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='attributenamevalue',
            old_name='name_attr',
            new_name='name',
        ),
    ]
