# Generated by Django 5.1.7 on 2025-03-28 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('creacion_y_gestion_de_productos', '0035_rename_name_attr_attributename_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attributename',
            old_name='name',
            new_name='name_attr',
        ),
        migrations.RenameField(
            model_name='attributenamevalue',
            old_name='name',
            new_name='name_attr',
        ),
    ]
