# Generated by Django 5.1.7 on 2025-03-30 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creacion_y_gestion_de_productos', '0037_alter_attributevalue_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attributevalue',
            name='value',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
