# Generated by Django 5.1.7 on 2025-03-30 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creacion_y_gestion_de_productos', '0038_alter_attributevalue_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attributevalue',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
