# Generated by Django 5.1.7 on 2025-04-01 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creacion_y_gestion_de_productos', '0039_alter_attributevalue_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='attributevalue',
            name='free_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attributevalue',
            name='price_extra',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
