# Generated by Django 5.1.7 on 2025-04-01 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creacion_y_gestion_de_productos', '0040_attributevalue_free_text_attributevalue_price_extra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attributevalue',
            name='price_extra',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True),
        ),
    ]
