# Generated by Django 5.1.7 on 2025-04-01 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('creacion_y_gestion_de_productos', '0041_alter_attributevalue_price_extra'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productattributevalue',
            name='name_attribute',
        ),
        migrations.RemoveField(
            model_name='producttemplateattribute',
            name='attribute',
        ),
        migrations.RemoveField(
            model_name='producttemplateattributevalue',
            name='attribute_value',
        ),
        migrations.RemoveField(
            model_name='productproduct',
            name='attributes',
        ),
        migrations.RemoveField(
            model_name='productproduct',
            name='product_template',
        ),
        migrations.RemoveField(
            model_name='producttemplateattributevalue',
            name='product_variant',
        ),
        migrations.RemoveField(
            model_name='producttemplateattribute',
            name='product_template',
        ),
        migrations.DeleteModel(
            name='ProductAttribute',
        ),
        migrations.DeleteModel(
            name='ProductAttributeValue',
        ),
        migrations.DeleteModel(
            name='ProductProduct',
        ),
        migrations.DeleteModel(
            name='ProductTemplateAttributeValue',
        ),
        migrations.DeleteModel(
            name='ProductTemplateAttribute',
        ),
    ]
