# Generated by Django 5.1.7 on 2025-04-01 19:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creacion_y_gestion_de_productos', '0042_remove_productattributevalue_name_attribute_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('attribute_values', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='creacion_y_gestion_de_productos.attributenamevalue')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='creacion_y_gestion_de_productos.producto')),
            ],
            options={
                'unique_together': {('attribute_values', 'product')},
            },
        ),
        migrations.AddField(
            model_name='producto',
            name='attributes',
            field=models.ManyToManyField(through='creacion_y_gestion_de_productos.ProductAttribute', to='creacion_y_gestion_de_productos.attributenamevalue'),
        ),
    ]
