# Generated by Django 5.1.7 on 2025-04-01 21:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creacion_y_gestion_de_productos', '0043_productattribute_producto_attributes'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productattribute',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='producto',
            name='attributes',
        ),
        migrations.AlterField(
            model_name='productattribute',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attribute_values', to='creacion_y_gestion_de_productos.producto'),
        ),
        migrations.RemoveField(
            model_name='productattribute',
            name='attribute_values',
        ),
        migrations.AddField(
            model_name='productattribute',
            name='attribute_values',
            field=models.ManyToManyField(to='creacion_y_gestion_de_productos.attributenamevalue'),
        ),
    ]
