# Generated by Django 5.1.7 on 2025-06-15 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryProduct',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('deleted_date', models.DateField(blank=True, null=True, verbose_name='Fecha de Eliminación')),
                ('category', models.CharField(max_length=50, unique=True, verbose_name='Descripcion')),
            ],
            options={
                'verbose_name': 'Categoria de Producto',
                'verbose_name_plural': 'Categorias de Productos',
            },
        ),
        migrations.CreateModel(
            name='MeasureUnit',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('deleted_date', models.DateField(blank=True, null=True, verbose_name='Fecha de Eliminación')),
                ('description', models.CharField(max_length=50, unique=True, verbose_name='Descripcion')),
            ],
            options={
                'verbose_name': 'Unidad de Medida',
                'verbose_name_plural': 'Unidades de Medidas',
            },
        ),
        migrations.CreateModel(
            name='NameAttribute',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('deleted_date', models.DateField(blank=True, null=True, verbose_name='Fecha de Eliminación')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre del atributo')),
            ],
            options={
                'verbose_name': 'Nombre atributo',
                'verbose_name_plural': 'Nombre atributo',
            },
        ),
        migrations.CreateModel(
            name='ProductoProductoModel',
            fields=[
                ('id_producto_producto', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField(blank=True, default='Descripción no disponible', null=True, verbose_name='Descripción')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
            ],
        ),
        migrations.CreateModel(
            name='ProductoTemplateModel',
            fields=[
                ('id_producto_template', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_base_producto', models.CharField(max_length=255, verbose_name='Nombre base del producto')),
                ('principio_activo', models.CharField(blank=True, max_length=255, null=True, verbose_name='Principio activo')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
            },
        ),
        migrations.CreateModel(
            name='ProveedorModel',
            fields=[
                ('id_proveedor', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_proveedor', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RecordAuditModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=100)),
                ('registro_id', models.IntegerField()),
                ('registro_nombre', models.CharField(max_length=250)),
                ('accion', models.CharField(max_length=10)),
                ('cambios', models.JSONField(blank=True, null=True)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TypeProduct',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('deleted_date', models.DateField(blank=True, null=True, verbose_name='Fecha de Eliminación')),
                ('type_product', models.CharField(choices=[('almacenable', 'Almacenable'), ('consumible', 'Consumible'), ('servicio', 'Servicio')], max_length=100, unique=True, verbose_name='Tipo de producto')),
            ],
            options={
                'verbose_name': 'Tipo de Producto',
                'verbose_name_plural': 'Tipos de Producto',
                'ordering': ['type_product'],
            },
        ),
        migrations.CreateModel(
            name='UserProvider',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('deleted_date', models.DateField(blank=True, null=True, verbose_name='Fecha de Eliminación')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre del usuario')),
            ],
            options={
                'verbose_name': 'Modelo Base',
                'verbose_name_plural': 'Modelos Base',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UsuarioModel',
            fields=[
                ('id_usuario', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_usuario', models.CharField(max_length=255)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('deleted_date', models.DateField(blank=True, null=True, verbose_name='Fecha de Eliminación')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='Nombre de la Categoría')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='products.category', verbose_name='Padre de la Categoria')),
            ],
            options={
                'verbose_name': 'Categoría de Producto',
                'verbose_name_plural': 'Categorías de Producto',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('deleted_date', models.DateField(blank=True, null=True, verbose_name='Fecha de Eliminación')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre de Producto')),
                ('description', models.TextField(blank=True, default='Descripción no disponible', null=True, verbose_name='Descripción')),
                ('presentation', models.TextField(blank=True, default='Presentación no disponible', null=True, verbose_name='Presentación')),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, verbose_name='Precio')),
                ('price_sale', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, verbose_name='Precio de Venta')),
                ('price_cost', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, verbose_name='Precio de Costo')),
                ('reference_code', models.CharField(blank=True, max_length=100, null=True, verbose_name='Código de Referencia')),
                ('bar_code', models.CharField(blank=True, max_length=100, null=True, verbose_name='Código de Barra')),
                ('internal_code', models.CharField(blank=True, max_length=100, null=True, verbose_name='Código de Producto Interno')),
                ('proveedor_code', models.CharField(blank=True, max_length=100, null=True, verbose_name='Código Producto del Proveedor')),
                ('ncm_code', models.CharField(blank=True, max_length=100, null=True, verbose_name='Código NCM del Producto')),
                ('niprod_code', models.CharField(blank=True, max_length=100, null=True, verbose_name='Niprod Carena')),
                ('categories', models.ManyToManyField(blank=True, to='products.category', verbose_name='Categoría de Producto')),
                ('measure_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.measureunit', verbose_name='Unidad de Medida')),
                ('type_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.typeproduct', verbose_name='Tipo de Producto')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
            },
        ),
        migrations.CreateModel(
            name='PriceHistoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor del precio')),
                ('price_type', models.CharField(choices=[('sale', 'Venta'), ('purchase', 'Compra'), ('price', 'Precio General')], max_length=10, verbose_name='Tipo de precio')),
                ('source', models.CharField(max_length=100, verbose_name='Fuente del precio')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de actualización')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='products.product', verbose_name='Producto')),
            ],
        ),
        migrations.CreateModel(
            name='ProductAttribute',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('deleted_date', models.DateField(blank=True, null=True, verbose_name='Fecha de Eliminación')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.nameattribute')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
            options={
                'verbose_name': 'Modelo Base',
                'verbose_name_plural': 'Modelos Base',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PrecioVentaModel',
            fields=[
                ('_id_precio_venta', models.AutoField(primary_key=True, serialize=False)),
                ('_precio_unitario', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('_create_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('id_producto_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precio_venta', to='products.productoproductomodel')),
            ],
            options={
                'verbose_name': 'Precio de Venta',
                'verbose_name_plural': 'Precios de Venta',
            },
        ),
        migrations.CreateModel(
            name='PrecioCompraModel',
            fields=[
                ('_id_precio_compra', models.AutoField(primary_key=True, serialize=False)),
                ('_precio_unitario', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('_create_date', models.DateTimeField(auto_now_add=True)),
                ('id_producto_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precio_compra', to='products.productoproductomodel')),
            ],
        ),
        migrations.CreateModel(
            name='PrecioBaseModel',
            fields=[
                ('_id_precio_base', models.AutoField(primary_key=True, serialize=False)),
                ('_precio_unitario', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('_create_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('id_producto_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precio_base', to='products.productoproductomodel')),
            ],
            options={
                'verbose_name': 'Precio de Base',
                'verbose_name_plural': 'Precios de Base',
            },
        ),
        migrations.AddField(
            model_name='productoproductomodel',
            name='id_producto_template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='producto_productos', to='products.productotemplatemodel', verbose_name='Producto template'),
        ),
        migrations.CreateModel(
            name='ProductoProveedorModel',
            fields=[
                ('id_producto_proveedor', models.AutoField(primary_key=True, serialize=False)),
                ('codigo_proveedor', models.CharField(blank=True, max_length=20, null=True, verbose_name='Código proveedor (régimen)')),
                ('id_producto_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proveedores', to='products.productoproductomodel', verbose_name='Producto producto')),
                ('id_proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='products.proveedormodel', verbose_name='Proveedor')),
            ],
        ),
        migrations.CreateModel(
            name='SupplierProduct',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('deleted_date', models.DateField(blank=True, null=True, verbose_name='Fecha de Eliminación')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='Producto')),
                ('supplier_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.userprovider', verbose_name='Proveedor')),
            ],
            options={
                'verbose_name': 'Producto Proveedor',
                'verbose_name_plural': 'Productos Proveedores',
            },
        ),
        migrations.CreateModel(
            name='FileUploadProductModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('deleted_date', models.DateField(blank=True, null=True, verbose_name='Fecha de Eliminación')),
                ('file_name', models.CharField(max_length=255)),
                ('name_supplier_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.userprovider', verbose_name='Proveedor')),
            ],
            options={
                'verbose_name': 'Relacion proveedor con Archivo csv',
            },
        ),
        migrations.CreateModel(
            name='UsuarioProveedorModel',
            fields=[
                ('id_usuario_proveedor', models.AutoField(primary_key=True, serialize=False)),
                ('id_proveedor', models.ForeignKey(db_column='id_proveedor', on_delete=django.db.models.deletion.CASCADE, to='products.proveedormodel')),
                ('id_usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, to='products.usuariomodel')),
            ],
        ),
        migrations.CreateModel(
            name='ValueAttribute',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('deleted_date', models.DateField(blank=True, null=True, verbose_name='Fecha de Eliminación')),
                ('value', models.CharField(max_length=100, verbose_name='Valor del atributo')),
                ('price_extra', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, verbose_name='Precio Extra')),
                ('free_text', models.TextField(blank=True, null=True)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.nameattribute')),
            ],
            options={
                'verbose_name': 'Valor atributo',
                'verbose_name_plural': 'Valor atributo',
            },
        ),
        migrations.CreateModel(
            name='AttributeNameValue',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('deleted_date', models.DateField(blank=True, null=True, verbose_name='Fecha de Eliminación')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.nameattribute', verbose_name='Nombre del Atributo')),
                ('values', models.ManyToManyField(to='products.valueattribute', verbose_name='Valores de Atributo')),
            ],
            options={
                'verbose_name': 'Nombre y valor del atributo',
                'verbose_name_plural': 'Nombre y valor del atributo',
            },
        ),
        migrations.CreateModel(
            name='VariantProduct',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('deleted_date', models.DateField(blank=True, null=True, verbose_name='Fecha de Eliminación')),
                ('sku', models.CharField(max_length=100, unique=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='Entidad Producto')),
            ],
            options={
                'verbose_name': 'Variante de producto',
                'verbose_name_plural': 'Variante de producto',
            },
        ),
        migrations.CreateModel(
            name='VariantAttribute',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('deleted_date', models.DateField(blank=True, null=True, verbose_name='Fecha de Eliminación')),
                ('attribute_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.nameattribute')),
                ('attribute_value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.valueattribute')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.variantproduct')),
            ],
            options={
                'verbose_name': 'Variante y atributos',
                'verbose_name_plural': 'Variante y atributos',
            },
        ),
        migrations.CreateModel(
            name='PriceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio actual')),
                ('price_type', models.CharField(choices=[('sale', 'Venta'), ('purchase', 'Compra'), ('price', 'Precio General')], max_length=10, verbose_name='Tipo de precio')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='active_price', to='products.product', verbose_name='Producto')),
            ],
            options={
                'unique_together': {('product', 'price_type')},
            },
        ),
    ]
