# Generated by Django 5.1.7 on 2025-06-15 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariomodel',
            name='id_usuario',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
