# Generated by Django 5.1.7 on 2025-04-08 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='measureunit',
            old_name='description',
            new_name='nombre',
        ),
    ]
