# Generated by Django 5.1.7 on 2025-07-03 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_usuariomodel_id_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='productoproductomodel',
            name='codigo_barras',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Codigo de Barra'),
        ),
        migrations.AddField(
            model_name='productoproductomodel',
            name='codigo_interno',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Código de Producto Interno'),
        ),
        migrations.AddField(
            model_name='productoproductomodel',
            name='codigo_ncm',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Código NCM del Producto'),
        ),
        migrations.AddField(
            model_name='productoproductomodel',
            name='codigo_niprod',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Niprod Carena'),
        ),
        migrations.AddField(
            model_name='productoproductomodel',
            name='codigo_proveedor',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Código Producto del Proveedor'),
        ),
        migrations.AddField(
            model_name='productoproductomodel',
            name='codigo_referencia',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Codigo de Referencia'),
        ),
        migrations.AlterField(
            model_name='productoproductomodel',
            name='descripcion',
            field=models.TextField(blank=True, default='Descripcion no disponible', null=True, verbose_name='Descripción'),
        ),
        migrations.DeleteModel(
            name='SupplierProduct',
        ),
    ]
