# Generated by Django 5.1.7 on 2025-07-03 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_productoproductomodel_codigo_barras_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productoproductomodel',
            name='codigo_proveedor',
        ),
        migrations.AddField(
            model_name='productoproductomodel',
            name='codigo_producto',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Código Producto'),
        ),
    ]
