# Generated by Django 5.1.7 on 2025-07-03 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_productoproductomodel_codigo_proveedor_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pricemodel',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='pricemodel',
            name='product',
        ),
        migrations.AlterModelOptions(
            name='productoproductomodel',
            options={'ordering': ['descripcion', 'presentacion'], 'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
        migrations.AddField(
            model_name='productoproductomodel',
            name='presentacion',
            field=models.CharField(default='Sin presentación', max_length=50, verbose_name='Presentación'),
        ),
        migrations.AddField(
            model_name='productoproductomodel',
            name='sku',
            field=models.CharField(default='SKU_TEMPORAL_001', max_length=30, unique=True, verbose_name='SKU'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productoproductomodel',
            name='unidad_medida',
            field=models.CharField(default='unidad', max_length=20, verbose_name='Unidad de medida'),
        ),
        migrations.AlterField(
            model_name='productoproductomodel',
            name='codigo_barras',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Código de Barras'),
        ),
        migrations.AlterField(
            model_name='productoproductomodel',
            name='codigo_interno',
            field=models.CharField(default='CODIGO_TEMPORAL_001', max_length=30, unique=True, verbose_name='Código Interno'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productoproductomodel',
            name='codigo_ncm',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Código NCM'),
        ),
        migrations.AlterField(
            model_name='productoproductomodel',
            name='codigo_niprod',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Código NIPROD / ANMAT'),
        ),
        migrations.AlterField(
            model_name='productoproductomodel',
            name='codigo_producto',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Código Producto'),
        ),
        migrations.AlterField(
            model_name='productoproductomodel',
            name='codigo_referencia',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Código de Referencia'),
        ),
        migrations.AlterField(
            model_name='productoproductomodel',
            name='descripcion',
            field=models.TextField(blank=True, default='Sin descripción', null=True, verbose_name='Descripción'),
        ),
        migrations.DeleteModel(
            name='PriceHistoryModel',
        ),
        migrations.DeleteModel(
            name='PriceModel',
        ),
    ]
