# Generated by Django 5.1.7 on 2025-04-08 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_remove_product_category_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoryproduct',
            name='measure_unite',
        ),
    ]
