# Generated by Django 5.1.7 on 2025-07-03 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_pricemodel_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productoproductomodel',
            name='codigo_barras',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Código de Barras'),
        ),
        migrations.AlterField(
            model_name='productoproductomodel',
            name='codigo_interno',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Código Interno'),
        ),
        migrations.AlterField(
            model_name='productoproductomodel',
            name='codigo_ncm',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Código NCM'),
        ),
        migrations.AlterField(
            model_name='productoproductomodel',
            name='codigo_niprod',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Código NIPROD / ANMAT'),
        ),
        migrations.AlterField(
            model_name='productoproductomodel',
            name='codigo_producto',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Código Producto'),
        ),
        migrations.AlterField(
            model_name='productoproductomodel',
            name='codigo_referencia',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Código de Referencia'),
        ),
        migrations.AlterField(
            model_name='productoproductomodel',
            name='presentacion',
            field=models.CharField(default='Sin presentación', max_length=100, null=True, verbose_name='Presentación'),
        ),
        migrations.AlterField(
            model_name='productoproductomodel',
            name='sku',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='SKU'),
        ),
        migrations.AlterField(
            model_name='productoproductomodel',
            name='unidad_medida',
            field=models.CharField(blank=True, default='unidad', max_length=50, null=True, verbose_name='Unidad de medida'),
        ),
    ]
