# Generated by Django 5.1.7 on 2025-04-09 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_remove_categoryproduct_measure_unite'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, default='Descripción no disponible', null=True, verbose_name='Descripcion'),
        ),
        migrations.AddField(
            model_name='product',
            name='presentation',
            field=models.TextField(blank=True, default='Presentacion no disponible', null=True, verbose_name='Presentacion'),
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True, verbose_name='Precio'),
        ),
        migrations.AddField(
            model_name='product',
            name='price_cost',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True, verbose_name='Precio de Costo'),
        ),
        migrations.AddField(
            model_name='product',
            name='price_sale',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True, verbose_name='Precio de Venta'),
        ),
    ]
