# Generated by Django 5.1.7 on 2025-07-03 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_productoproductomodel_codigo_barras_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productoproductomodel',
            name='codigo_niprod',
        ),
        migrations.AlterField(
            model_name='productoproductomodel',
            name='codigo_ncm',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Código NIPROD / ANMAT'),
        ),
    ]
