# Generated by Django 5.1.7 on 2025-04-09 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_product_description_product_presentation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeProduct',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('deleted_date', models.DateField(blank=True, null=True, verbose_name='Fecha de Eliminación')),
                ('tipo', models.CharField(choices=[('almacenable', 'Almacenable'), ('consumible', 'Consumible'), ('servicio', 'Servicio')], max_length=100, unique=True, verbose_name='Tipo de producto')),
            ],
            options={
                'verbose_name': 'Tipo de Producto',
                'verbose_name_plural': 'Tipos de Producto',
                'ordering': ['tipo'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='bar_code',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Código de Barra'),
        ),
        migrations.AddField(
            model_name='product',
            name='internal_code',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Código de Producto Interno'),
        ),
        migrations.AddField(
            model_name='product',
            name='ncm_code',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Código NCM del Producto'),
        ),
        migrations.AddField(
            model_name='product',
            name='niprod_code',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Niprod Carena'),
        ),
        migrations.AddField(
            model_name='product',
            name='proveedor_code',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Código Producto del Proveedor'),
        ),
        migrations.AddField(
            model_name='product',
            name='reference_code',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Código de Referencia'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, default='Descripción no disponible', null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='product',
            name='presentation',
            field=models.TextField(blank=True, default='Presentación no disponible', null=True, verbose_name='Presentación'),
        ),
    ]
