# Generated by Django 5.1.7 on 2025-07-03 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_remove_productoproductomodel_codigo_niprod_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productoproductomodel',
            name='codigo_niprod',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Código NIPROD / ANMAT'),
        ),
        migrations.AlterField(
            model_name='productoproductomodel',
            name='codigo_ncm',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Código NCM'),
        ),
    ]
