# Generated by Django 5.1.7 on 2025-04-09 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_typeproduct_product_bar_code_product_internal_code_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='typeproduct',
            options={'ordering': ['type_product'], 'verbose_name': 'Tipo de Producto', 'verbose_name_plural': 'Tipos de Producto'},
        ),
        migrations.RenameField(
            model_name='typeproduct',
            old_name='tipo',
            new_name='type_product',
        ),
    ]
