# Generated by Django 5.1.7 on 2025-07-03 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_productoproductomodel_codigo_niprod_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productoproductomodel',
            name='codigo_barras',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, unique=True, verbose_name='Código de Barras'),
        ),
        migrations.AlterField(
            model_name='productoproductomodel',
            name='codigo_interno',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, unique=True, verbose_name='Código Interno'),
        ),
        migrations.AlterField(
            model_name='productoproductomodel',
            name='codigo_ncm',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, unique=True, verbose_name='Código NCM'),
        ),
        migrations.AlterField(
            model_name='productoproductomodel',
            name='codigo_niprod',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, unique=True, verbose_name='Código NIPROD / ANMAT'),
        ),
        migrations.AlterField(
            model_name='productoproductomodel',
            name='codigo_producto',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, unique=True, verbose_name='Código Producto'),
        ),
        migrations.AlterField(
            model_name='productoproductomodel',
            name='codigo_referencia',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, unique=True, verbose_name='Código de Referencia'),
        ),
        migrations.AlterField(
            model_name='productoproductomodel',
            name='sku',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, unique=True, verbose_name='SKU'),
        ),
    ]
