# Generated by Django 5.1.7 on 2025-04-09 04:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_typeproduct_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='type_product',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.typeproduct', verbose_name='Tipo de Producto'),
        ),
    ]
