# Generated by Django 5.1.7 on 2025-07-12 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_productoproductomodel_codigo_barras_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='preciocompramodel',
            name='_precio_con_iva',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='preciocompramodel',
            name='_precio_sin_iva',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='preciocompramodel',
            name='_precio_sugerido',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
