# Generated by Django 5.1.7 on 2025-04-09 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(blank=True, to='products.category', verbose_name='Categoría de Producto'),
        ),
    ]
