# Generated by Django 5.1.7 on 2025-07-12 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_preciocompramodel__precio_con_iva_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='preciocompramodel',
            old_name='_precio_con_iva',
            new_name='_precio_compra_con_iva',
        ),
        migrations.RenameField(
            model_name='preciocompramodel',
            old_name='_precio_sin_iva',
            new_name='_precio_compra_sin_iva',
        ),
        migrations.RenameField(
            model_name='preciocompramodel',
            old_name='_precio_sugerido',
            new_name='_precio_compra_sugerido',
        ),
        migrations.RenameField(
            model_name='preciocompramodel',
            old_name='_precio_unitario',
            new_name='_precio_compra_unitario',
        ),
    ]
