# Generated by Django 5.1.7 on 2025-04-09 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_product_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='category',
            new_name='categories',
        ),
    ]
