# Generated by Django 5.1.7 on 2025-04-10 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_alter_product_price_alter_product_price_cost_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='type_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.typeproduct', verbose_name='Tipo de Producto'),
        ),
    ]
