# Generated by Django 5.1.7 on 2025-04-17 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_alter_product_measure_unit'),
    ]

    operations = [
        migrations.CreateModel(
            name='NameAttribute',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('deleted_date', models.DateField(blank=True, null=True, verbose_name='Fecha de Eliminación')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre del atributo')),
            ],
            options={
                'verbose_name': 'Nombre atributo',
                'verbose_name_plural': 'Nombre atributo',
            },
        ),
        migrations.CreateModel(
            name='ProductAttribute',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('deleted_date', models.DateField(blank=True, null=True, verbose_name='Fecha de Eliminación')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.nameattribute')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
            options={
                'verbose_name': 'Modelo Base',
                'verbose_name_plural': 'Modelos Base',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ValueAttribute',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('deleted_date', models.DateField(blank=True, null=True, verbose_name='Fecha de Eliminación')),
                ('value', models.CharField(max_length=100, verbose_name='Valor del atributo')),
                ('price_extra', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, verbose_name='Precio Extra')),
                ('free_text', models.TextField(blank=True, null=True)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.nameattribute')),
            ],
            options={
                'verbose_name': 'Valor atributo',
                'verbose_name_plural': 'Valor atributo',
            },
        ),
        migrations.CreateModel(
            name='AttributeNameValue',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('deleted_date', models.DateField(blank=True, null=True, verbose_name='Fecha de Eliminación')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.nameattribute', verbose_name='Nombre del Atributo')),
                ('values', models.ManyToManyField(to='products.valueattribute', verbose_name='Valores de Atributo')),
            ],
            options={
                'verbose_name': 'Nombre y valor del atributo',
                'verbose_name_plural': 'Nombre y valor del atributo',
            },
        ),
    ]
