# Generated by Django 5.1.7 on 2025-04-17 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_nameattribute_productattribute_valueattribute_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='valueattribute',
            name='attribute',
        ),
    ]
