# Generated by Django 5.1.7 on 2025-04-17 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_valueattribute_attribute'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='valueattribute',
            name='attribute',
        ),
    ]
