# Generated by Django 5.1.7 on 2025-04-17 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_remove_valueattribute_attribute'),
    ]

    operations = [
        migrations.AddField(
            model_name='valueattribute',
            name='attribute',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='products.nameattribute'),
            preserve_default=False,
        ),
    ]
