# Generated by Django 5.1.7 on 2025-04-17 19:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_valueattribute_attribute'),
    ]

    operations = [
        migrations.CreateModel(
            name='VariantProduct',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('deleted_date', models.DateField(blank=True, null=True, verbose_name='Fecha de Eliminación')),
                ('sku', models.CharField(max_length=100, unique=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='Entidad Producto')),
            ],
            options={
                'verbose_name': 'Variante de producto',
                'verbose_name_plural': 'Variante de producto',
            },
        ),
        migrations.CreateModel(
            name='VariantAttribute',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('deleted_date', models.DateField(blank=True, null=True, verbose_name='Fecha de Eliminación')),
                ('attribute_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.nameattribute')),
                ('attribute_value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.valueattribute')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.variantproduct')),
            ],
            options={
                'verbose_name': 'Variante y atributos',
                'verbose_name_plural': 'Variante y atributos',
            },
        ),
    ]
