# Generated by Django 5.1.7 on 2025-04-19 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0023_variantproduct_variantattribute'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(blank=True, null=True, to='products.category', verbose_name='Categoría de Producto'),
        ),
    ]
