# Generated by Django 5.1.7 on 2025-04-30 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0027_rename_product_supplierproduct_product_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileUploadProductModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('deleted_date', models.DateField(blank=True, null=True, verbose_name='Fecha de Eliminación')),
                ('name_supplier', models.CharField(max_length=50, verbose_name='Nombre del Proveedor')),
            ],
            options={
                'verbose_name': 'Nombre del Proveedor',
            },
        ),
    ]
