# Generated by Django 5.1.7 on 2025-04-30 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0028_fileuploadproductmodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fileuploadproductmodel',
            options={'verbose_name': 'Relacion proveedor con Archivo csv'},
        ),
        migrations.RemoveField(
            model_name='fileuploadproductmodel',
            name='name_supplier',
        ),
        migrations.AddField(
            model_name='fileuploadproductmodel',
            name='name_supplier_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='products.user', verbose_name='Proveedor'),
            preserve_default=False,
        ),
    ]
