# Generated by Django 5.1.7 on 2025-04-30 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0029_alter_fileuploadproductmodel_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileuploadproductmodel',
            name='file_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
