# Generated by Django 5.1.7 on 2025-05-07 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0030_fileuploadproductmodel_file_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecordAuditModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=100)),
                ('registro_id', models.IntegerField()),
                ('accion', models.CharField(max_length=10)),
                ('cambios', models.JSONField(blank=True, null=True)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
