# Generated by Django 5.1.7 on 2025-05-08 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0031_recordauditmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='recordauditmodel',
            name='registro_nombre',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
