# Generated by Django 5.1.7 on 2025-05-08 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0032_recordauditmodel_registro_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(blank=True, to='products.category', verbose_name='Categoría de Producto'),
        ),
    ]
